---
- name: install chrony
  package:
    name: chrony
    state: present
  become: true

- name: Configure chrony
  template:
    src: chrony.conf.RedHat.j2
    dest: /etc/chrony.conf
  notify: restart chronyd

- name: start chronyd
  service:
    name: chronyd
    state: started
    enabled: yes
